### ISSUE TITLE
[feature-request] Auto-generate commit messages in magit.

### ISSUE THREAD

**Issue by CsBigDataHub** [s-kostyaev/ellama#105]
Prompt - https://github.com/ywkim/gpt-commit/blob/66badff3de08055f69b9ff892f9d6580b01268db/gpt-commit.el#L66

Commandline examples - https://github.com/ikramhasan/AI-Dev-Scripts/blob/main/ai_commit

Other commandline project - https://github.com/di-sukharev/opencommit

**Comment by s-kostyaev** [comment]
Hi @CsBigDataHub 

Not sure if it is really useful. Helpful commit message says why changes made, not what changed. And LLM can't extract the reason from diff.

**Comment by eras** [comment]
However, have you looked at the commits in this repository? :wink: 

Projects have different commit message conventions, but I think the first line of commit should say what was changed. The body, if present, can tell more: sometimes it's why, sometimes it's just in higher level to get an idea of the change without looking into the code.

Is [this explanation](https://chat.openai.com/share/fb54632f-0938-4a29-b133-acc1464b7bae) for [42da4b2](https://github.com/s-kostyaev/ellama/commit/42da4b22d5c923b6c6f6139e86e8d18595b5fa24) poor?

**Comment by CsBigDataHub** [comment]
> Hi @CsBigDataHub 
> 
> 
> 
> Not sure if it is really useful. Helpful commit message says why changes made, not what changed. And LLM can't extract the reason from diff.

Hi @s-kostyaev totally agree but this feature can help speedup the commit writing message with more detail. Of course generated content can be edited. Please see Opencommit projects prompt.

**Comment by mcraveiro** [comment]
Actually, I wasn't too sold on this until I saw the example above, which I'll paste here for anyone else reading this thread. I now think this is quite useful.

![Screenshot from 2024-04-25 08-33-17](https://github.com/s-kostyaev/ellama/assets/180654/252b1d1a-e784-40f7-ac89-6b37fc129974)
