### ISSUE TITLE
Feature request: make "ollama-binary" accept the basename of the executable

### ISSUE THREAD

**Issue by hab25** [s-kostyaev/ellama#109]
I.e. have 
```elisp
(setopt ollama-binary "ollama")
```

work.

This supports the use-case where the absolute path to ollama changes at runtime. E.g. when using something like https://github.com/astoff/buffer-env. 

With this change, `ellama` will be aware each time the user (implicitly) changes their desired `ollama` by updating their `exec-path` variable.

I think the only change needed is to remove this check:
https://github.com/s-kostyaev/ellama/blob/6e6ec8e28b8ce32ff207b1b026aaaeddc1bd8239/ellama.el#L1123C49-L1123C85

**Comment by s-kostyaev** [comment]
We cant remove this check. It prevents errors for users without `ollama` installed. It should work out of the box if you update not only `exec-path` but also `ellama-ollama-binary`.
This code will work for users without configured `exec-path` if they set `ellama-ollama-binary`.
Not sure if we can handle correctly all the cases.

**Comment by s-kostyaev** [comment]
Also, is this real case or imaginable?
