### ISSUE TITLE
Context for new sessions

### ISSUE THREAD

**Issue by tbatchelli** [s-kostyaev/ellama#112]
Use case: when I want to start a new session, I might want to first build the context before I send the prompt and start a new session.

Current state: context is attached to sessions, so if the session does not exist you can't attach context to it. When adding context and then creating a new session the context is added to the previous session instead. To start a new session with context you need to first create a session with a bogus prompt, which will get a (confused) response from the LLM, and then add the context and then run a new prompt in this new session, and then the second prompt has the context. 

One option would be that the context is added in a session-free stack, and that only when you are about to issue a prompt the context is attached to the session before the chat is sent to the LLM

**Comment by s-kostyaev** [comment]
If you have no active sessions it will be added to temporal location (variable) and will be used in new session.
You can kill buffer with previous session instead of prompting with dummy message

**Comment by s-kostyaev** [comment]
Should be fixed now
