### ISSUE TITLE
Wrong org formatting + Garbled text

### ISSUE THREAD

**Issue by liar666** [s-kostyaev/ellama#117]
Hi,

Almost every time I `ask-selection`, I get both wrong org output & garbled text.

Here is an MVE:
```
** User:
generate tikz picture with a rectangle in blue

** Ellama:
Here is your TikZ code for a blue rectangle: #+END_SRC \documentclass{article}
\usepackage{tikz} \begin{document}
\begin{tikzpicture} \node[rectangle, draw=blue, fill=blue!20] (mynode) {Text};
\end{tikzpicture}
\end{document}~`~This code will create a rectangle with a blue border and light
blue filling. You can replace 'Text' with your desired text or other TikZ
elements.
```

As you can see, there are 2 problems:
- Code block starts with `~+END_SRC`! => wrong org output 
- Code is not formatted correctly (not that much the case here though) and code+text got mixed => garbled text

I'm not sure if you're reformatting the text after/during generation, or if it's an automatic process in my DoomEmacs/Org config, but it results in bad out, that takes more time for me to reformat manually than generating myself, thus rendering the whole usage of ellama pointless.

PS: Not sure if it is related to https://github.com/s-kostyaev/ellama/issues/35 (which is closed, thus supposed to be solved)?

**Comment by s-kostyaev** [comment]
Hi @liar666
Both problems is a result of code in `ellama`.
Try to use ellama with `markdown` instead of `org`:
```elisp
(setq ellama-major-mode 'markdown-mode)
```

**Comment by s-kostyaev** [comment]
I will try to provide more general fix.

**Comment by s-kostyaev** [comment]
Also which model do you use? Have you tried other models?

**Comment by liar666** [comment]
Hi,

Thanks for your very quick answer.

I'm using `orionstar/orion14b-q4:latest`.

I just discovered `ellama-fill-paragraphs`. Setting it it `nil` Seems to solve the main problem of garbled text.
