### ISSUE TITLE
error when asking a question

### ISSUE THREAD

**Issue by ronspe** [s-kostyaev/ellama#12]
"Hi,
I installed ollama and zephyr like this:
```
> curl https://ollama.ai/install.sh | sh
> ollama run zephyr
```
This functions well, I can ask a question from the prompt.
The ollama version is 0.1.8

I have used the exact use-package setup as you gave as an example in the README.md.

But the ellama package gives me this error when asking a question with ellama-ask:
```
error in process filter: llm-request-callback-in-buffer: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_27>, 1
error in process filter: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_27>, 1
```

The above error mentioned a "llm-request" and you mentioned in the README.md :"Switched from ollama API to llm library"
Could it be that the setup mentioned in the README.md is not relevant anymore?
What could cause this problem?

Thanks!

**Comment by ronspe** [comment]
Hi,

Thank you for your quick response!
I found the issue by using your M-x toggle-debug-on-error suggestion.

The problem was that I had the wrong version of zephyr.
After downloading the version as specified in the use-package with 
`ollama run zephyr:7b-alpha-q5_K_M ` the errors where gone and I got a response in Emacs using ellama-ask.

Thanks again!

**Comment by s-kostyaev** [comment]
There is zephyr:7b-beta-q5_K_M already and it's better 😃
