### ISSUE TITLE
No context is sent with `ellama-ask-about` with prefix arg

### ISSUE THREAD

**Issue by ahyatt** [s-kostyaev/ellama#122]
If I want to start a new session, and ask ellama about a particular buffer or selection, I can do C-u M-x ellama-ask-about.  This does start a new session, but the context is not included.

**Comment by s-kostyaev** [comment]
For now it adds in current session. I will fix it. I have a plan to rework universal arg functionality.

**Comment by s-kostyaev** [comment]
As a workaround you can kill buffer with active session before all your actions.
