### ISSUE TITLE
[BUG?] ellama fails with inscrutable error

### ISSUE THREAD

**Issue by NightMachinery** [s-kostyaev/ellama#123]
I get this error when I try to use ellama on a new installation of emacs. I can't really figure anything from this stacktrace ...

```lisp
Debugger entered--Lisp error: (wrong-type-argument (or eieio-object cl-structure-object oclosure) nil)
  signal(wrong-type-argument ((or eieio-object cl-structure-object oclosure) nil))
  slot-value(nil type)
  plz-media-type-name(nil)
  plz-media-type-symbol(nil)
  plz-media-type--find(((text/event-stream . #<plz-event-source:text/event-stream plz-event-source:text/event-stream-15555dba951e>) (application/json . #<plz-media-type:application/json plz-media-type:application/json-155560118e60>) (application/octet-stream . #<plz-media-type:application/octet-stream plz-media-type:application/octet-stream-155560118e80>) (application/xml . #<plz-media-type:application/xml plz-media-type:application/xml-155560118e94>) (text/html . #<plz-media-type:text/html plz-media-type:text/html-155560118e98>) (text/xml . #<plz-media-type:text/xml plz-media-type:text/xml-155560118eac>) (t . #<plz-media-type:application/octet-stream plz-media-type:application/octet-stream-155560118eb0>)) nil)
  plz-media-type-of-response(((text/event-stream . #<plz-event-source:text/event-stream plz-event-source:text/event-stream-15555dba951e>) (application/json . #<plz-media-type:application/json plz-media-type:application/json-155560118e60>) (application/octet-stream . #<plz-media-type:application/octet-stream plz-media-type:application/octet-stream-155560118e80>) (application/xml . #<plz-media-type:application/xml plz-media-type:application/xml-155560118e94>) (text/html . #<plz-media-type:text/html plz-media-type:text/html-155560118e98>) (text/xml . #<plz-media-type:text/xml plz-media-type:text/xml-155560118eac>) (t . #<plz-media-type:application/octet-stream plz-media-type:application/octet-stream-155560118eb0>)) #s(plz-response :version 1.1 :status 200 :headers ((proxy-agent . "gost/2.11.5")) :body ""))
  plz-media-type-process-filter(#<process plz-request-curl> ((text/event-stream . #<plz-event-source:text/event-stream plz-event-source:text/event-stream-15555dba951e>) (application/json . #<plz-media-type:application/json plz-media-type:application/json-155560118e60>) (application/octet-stream . #<plz-media-type:application/octet-stream plz-media-type:application/octet-stream-155560118e80>) (application/xml . #<plz-media-type:application/xml plz-media-type:application/xml-155560118e94>) (text/html . #<plz-media-type:text/html plz-media-type:text/html-155560118e98>) (text/xml . #<plz-media-type:text/xml plz-media-type:text/xml-155560118eac>) (t . #<plz-media-type:application/octet-stream plz-media-type:application/octet-stream-155560118eb0>)) "Proxy-Agent: gost/2.11.5\15\n\15\n")
  #f(compiled-function (process chunk) #<bytecode -0x1b9a9e39f22edad4>)(#<process plz-request-curl> "Proxy-Agent: gost/2.11.5\15\n\15\n")
```

**Comment by s-kostyaev** [comment]
I will check it out.
Plz in stack trace looks interesting. Maybe @ahyatt knows what it means?

**Comment by ahyatt** [comment]
plz is how we now do requests, which uses curl and actually parses to spec, instead of the pretty hacky things we were doing before.

@NightMachinery, can you share how you set up your provider, and what operation you are doing?

@r0man, in case he might know what's going on just from the stack trace.

**Comment by r0man** [comment]
Looks like a mismatch of the content type returned in the response and the registered one. I need more information. Which provider? Are you using a proxy? Can you somehow provide the response of this request? Is there a hidden plz buffer that contains the response?

**Comment by r0man** [comment]
@NightMachinery I had a closer look at the stacktrace (I was on mobile yesterday). It seems you were using a proxy (`gost/2.11.5`). 

Could you please try to:
- Evaluate https://github.com/ahyatt/llm/blob/main/plz-media-type.el
- Evaluate https://github.com/ahyatt/llm/blob/main/plz-event-source.el
- Try your request again and report back

If this still does not work it would be good to get the response. I think you can find it in a hidden buffer called `plz-request-xxxx` where the x's are some random number.

**Comment by r0man** [comment]
So, I just tried the gost proxy locally with Ollama/OpenAI, and it seems to work with the changes in the main branch of llm.
@ahyatt Let's cut a 16.1 release with the proxy changes?

**Comment by NightMachinery** [comment]
Evaluating these two files indeed solved the issue!
- https://github.com/ahyatt/llm/blob/main/plz-media-type.el
- https://github.com/ahyatt/llm/blob/main/plz-event-source.el

---
More info:
- I am using a gost proxy. I use this proxy also on my other emacs installation on my laptop (this new one is on a remote VPS), and it works fine there. So I am not sure if the proxy is to blame.
- There is no `plz` buffer in `switch-to-buffer`.

Here is the registered provider `ellama-provider`:
```
#s(llm-openai-compatible nil nil nil "REDACTED" "llama3-70b-8192" "llama3-70b-8192" "https://api.groq.com/openai/v1")
```

**Comment by r0man** [comment]
Hi @NightMachinery, ok perfect. Thanks for reporting back. Let's wait for @ahyatt to cut a release, then this should be resolved. To switch to hidden/invisible buffers, see https://www.emacswiki.org/emacs/InvisibleBuffers . But we don't need this now.

**Comment by s-kostyaev** [comment]
Closing this as issue resolved in new release of llm. @ahyatt thank you for calling for @r0man 
@r0man thank you for fixing issue
@NightMachinery Thank you for report
