### ISSUE TITLE
Code complete - Only 1st code block is added to current buffer

### ISSUE THREAD

**Issue by GitHubGeek** [s-kostyaev/ellama#129]
Summary: when using ellama-code-complete in an existing buffer, only the 1st code block is added to current buffer. Any non-code text and 2nd code block are missing.

Ollama terminal output showing 2 blocks of code (Model: `phind-codellama:34b-v2`)

![image](https://github.com/s-kostyaev/ellama/assets/265551/098e9719-c1f0-4bfa-b046-158fa72d2cf4)

Running ellama-code-complete:

![image](https://github.com/s-kostyaev/ellama/assets/265551/7d207199-883d-430d-9aaf-bd1e07ab7e9e)

Seems to me Ellama filtered out any text outside the 1st Markdown code block.

It'd be great if the non-code output is inserted as code comments, and the 2nd code block is also included in the buffer.

**Comment by s-kostyaev** [comment]
> It'd be great if the non-code output is inserted as code comments, and the 2nd code block is also included in the buffer.

Sounds like a good idea. I will think how to implement it.

**Comment by s-kostyaev** [comment]
Until it will be implemented as a workaround you can use chat or `ellama-ask-about` instead.

**Comment by GitHubGeek** [comment]
Is there a config option to have the output in plain text instead of markdown?

**Comment by s-kostyaev** [comment]
> Is there a config option to have the output in plain text instead of markdown?

try this
```emacs-lisp
(setopt ellama-major-mode 'fundamental-mode)
```

**Comment by GitHubGeek** [comment]
Seem to have no impact? My doom emacs config.el section:

```elisp
(use-package! ellama
  :config
  (setopt ellama-language "English")
  (require 'llm-ollama)
  (setopt ellama-major-mode 'fundamental-mode)
  (setopt ellama-provider
          (make-llm-ollama
           :chat-model "phind-codellama:34b-v2"
           :embedding-model "phind-codellama:34b-v2")))
```

**Comment by s-kostyaev** [comment]
> Seem to have no impact? My doom emacs config.el section:
> 
> ```emacs-lisp
> (use-package! ellama
>   :config
>   (setopt ellama-language "English")
>   (require 'llm-ollama)
>   (setopt ellama-major-mode 'fundamental-mode)
>   (setopt ellama-provider
>           (make-llm-ollama
>            :chat-model "phind-codellama:34b-v2"
>            :embedding-model "phind-codellama:34b-v2")))
> ```

Please open another issue for this. I will see later.

**Comment by s-kostyaev** [comment]
@GitHubGeek try to improve template:
```emacs-lisp
(setopt ellama-code-complete-prompt-template "Continue the following code, only write new code in format ```language\n...\n```:\n```\n%s\n```\nWrite all the code in single code block.")
```
After that try your original prompt.
