### ISSUE TITLE
error in process filter: Wrong number of arguments: #<subr F616e6f6e796d6f75732d6c616d626461_anonymous_lambda_27>, 1

### ISSUE THREAD

**Issue by artelse** [s-kostyaev/ellama#13]
Title says it all. This is my first install of Ollama and Ellama.
Running latest version 20231105.1147

**Comment by s-kostyaev** [comment]
Please M-x toggle-debug-on-error and paste here debugger window content. Which version of emacs do you use?

**Comment by artelse** [comment]
Enabled the debugger and found it couldn't find the model. Fixed this in my init and now I don't get the error. However, when I try to summarize a region of text, it causes 100% cpu and the summary is printed extremely slow. This is on Linux and Emacs 30.0.50, not nightly but from a few weeks ago.

**Comment by s-kostyaev** [comment]
Which hardware do you have? Cpu, GPU, ram. And which model do you use? Default one?

**Comment by artelse** [comment]
Hardware might be the problem:
Intel Core i7-5600, HD Graphics 5500
So it might just run on cpu with 16GB RAM.
Model is zephyr, perhaps switch to a lighter model; any recommendation? Intended use is coding and general text use.

**Comment by s-kostyaev** [comment]
You can try:
- lower quantization of zephyr (like [7b-beta-q2_K](https://ollama.ai/library/zephyr:7b-beta-q2_K), [7b-beta-q3_K_S](https://ollama.ai/library/zephyr:7b-beta-q3_K_S), [7b-beta-q3_K_M](https://ollama.ai/library/zephyr:7b-beta-q3_K_M), [7b-beta-q3_K_L](https://ollama.ai/library/zephyr:7b-beta-q3_K_L)
- lighter models, like [orca-mini:3b-q4_0](https://ollama.ai/library/orca-mini:3b-q4_0) or [starcoder:1b](https://ollama.ai/library/starcoder:1b), [starcoder:3b](https://ollama.ai/library/starcoder:3b) for coding
- deploy ollama on more powerful machine and connect ellama to it (on cloud provider, for example)
- use OpenAI of Google api

**Comment by artelse** [comment]
Thanks tested with orca-mini and it works. Still a bit slow, so might go for a server solution or get a better GPU. When I switch to an org-mode buffer and ask to write some code, it still assumes ``` markdown syntax for the code output.

**Comment by s-kostyaev** [comment]
Org syntax should be supported separately. I will think about it later.
