### ISSUE TITLE
Ollama - Can't get plain text output

### ISSUE THREAD

**Issue by GitHubGeek** [s-kostyaev/ellama#130]
Here's my doom emacs config.el section:

```elisp
(use-package! ellama
  :config
  (setopt ellama-language "English")
  (require 'llm-ollama)
  (setopt ellama-major-mode 'fundamental-mode)
  (setopt ellama-provider
          (make-llm-ollama
           :chat-model "phind-codellama:34b-v2"
           :embedding-model "phind-codellama:34b-v2")))
```

With the line `(setopt ellama-major-mode 'fundamental-mode)` I'm still getting markdown (or formatted) text when running `ellama-code-complete` in a typescript buffer

p.s. related to #129

**Comment by s-kostyaev** [comment]
> `ellama-code-complete` in a typescript buffer

Which model do you use? It's model outputs markdown.

**Comment by s-kostyaev** [comment]
@GitHubGeek if you want to complete code you need to use base code model, not instruction tuned.

**Comment by s-kostyaev** [comment]
Not a bug
