### ISSUE TITLE
ellama-chat

### ISSUE THREAD

**Issue by 2jt** [s-kostyaev/ellama#14]
hi How do you use ellama-chat? Every time you want to continue the chat, you call ellama-chat, input stuff in the minibuffer and see the accumulative results in *ellama* buffer?

I tried to find if there was a possibility to input text directly in *ellama* buffer and evaluate it (for example C-c or something). Long, formatted text cannot be inputted in minibuffer comfortably.

Thanks for the plugin.

**Comment by s-kostyaev** [comment]
Hi. There is open PR with keymap for ellama commands, it will be merged later. For long text probably more useful `ellama-ask-about`, that gets current selection or current buffer if there is no active selection and your question or instruction from interactive minibuffer. For now there is no way to input text directly in ellama buffer. And for now I don't know how to implement it to be useful. Than you for feedback.

**Comment by 2jt** [comment]
`ask-about` does the job. It's confusing however, that after selecting some text and then hitting `ask-about` command, it still prompts with empty minibuffer asking for input. Just hitting enter at this point takes the selected text as input and starts looking for an answer as you've mentioned. 

Thanks

**Comment by s-kostyaev** [comment]
I can add command like `ellama-send-to-chat` or something like that. I will think about it.

**Comment by s-kostyaev** [comment]
@2jt I have added `ellama-ask-selection` and `ellama-ask-line` commands. Feedback is welcome.
