### ISSUE TITLE
Question: given list of words in foreign language, how to generate table with translations?

### ISSUE THREAD

**Issue by suhail-singh** [s-kostyaev/ellama#145]
I have a process for generating a list of words from a foreign language
document.  I would like to generate a table from this list where for each word
the local LLM translation model is used to come up with the English language
meaning.

How can this be done reliably?  My preference would be for this to be scriptable
as well (via Elisp).  Is this something Ellama is suited for, or is this better
addressed by one of the other LLM Elisp packages?

**Comment by s-kostyaev** [comment]
See ellama-chain function. There are couple of example usages as well.

**Comment by s-kostyaev** [comment]
If you need more control you can use `llm` library directly. Or create some feature requests here.
