### ISSUE TITLE
[Feature request] add a customizeable boolean option that enables the following behaviour: whenever a user switches to a buffer that is in `ellama-session-mode`,  update `ellama--current-session-id` to point to that buffer

### ISSUE THREAD

**Issue by hab25** [s-kostyaev/ellama#152]
Use-case: I have a custom command that sends the same query to multiple `ellama-providers`, each on a separate window and buffer, so that I can easily and quickly compare with or switch to another LLM if I don't like the first's answer. However this is not working as well as I'd like because, with this setup, `#'ellama-chat` always targets the last-spawned session even as I switch between the windows.

While I could probably set `ellama--current-session-id` appropriately by using `window-buffer-change-functions` and `window-selection-change-functions` and taking inspiration from `#'ellama-load-session`, I don't want to build on a private (i.e. containing "--" in its name) variable because that would be too fragile against internal changes in ellama.

**Comment by s-kostyaev** [comment]
Hi @hab25 for now you can just switch to buffer with session you need and `ellama-chat` will sent message to it. If it doesn't work, it's a bug. Later I have a plan to improve interactive usage.

**Comment by s-kostyaev** [comment]
@hab25  I don't want to make this variables public, but new release should meet your needs.
