### ISSUE TITLE
`ellama-generate-commit-message` outputs at the cursor point instead of in a new buffer

### ISSUE THREAD

**Issue by yonta** [s-kostyaev/ellama#155]
When `ellama-generate-commit-message` is executed, the generated message is inserted at the current cursor position instead of in a new `ellama` buffer."

## Minimal Environment (init.el)

```elisp
(require 'ellama)
```

## Screenshot

![image](https://github.com/user-attachments/assets/477c3622-a5a8-4da9-9236-80acf53a5c8f)

**Comment by s-kostyaev** [comment]
It's not a bug. I use it together with `magit-commit` command. Why do you need new buffer?

**Comment by yonta** [comment]
Thx to reply.
I see.

I am using ace-window. 
When I run ellama-generate-commit-message, ace-window asks which window to use, so I mistakenly thought that opening in a different buffer was the correct action.
