### ISSUE TITLE
[Q] How to input a newline in "Ask ellama:" minibuffer?

### ISSUE THREAD

**Issue by k4r4b3y** [s-kostyaev/ellama#157]
How can I use the "Ask ellama:" minibuffer for multiple-line queries of mine?  Do I have to type out my multi-lined question in a scratch buffer, and then yank-paste it into the minibuffer?

**Comment by s-kostyaev** [comment]
You can yank-paste or use `ellama-ask-selection` command for example. Or write text in the minibuffer, but instead of `<RET>` use `M-j`.
