### ISSUE TITLE
No such file or directory, plz-event-source

### ISSUE THREAD

**Issue by k4r4b3y** [s-kostyaev/ellama#165]
I use the ellama, plz and llm packages from their git repos.  Here's how I pull them into my emacs' `init.el` file:

```
#+begin_src emacs-lisp :tangle ./emacs/.config/emacs/init.el :mkdirp yes
(use-package plz
  :if (file-exists-p "~/.local/src/plz.el")
  :load-path "~/.local/src/plz.el"
  )
#+end_src

#+begin_src emacs-lisp :tangle ./emacs/.config/emacs/init.el :mkdirp yes
(use-package llm
  :if (file-exists-p "~/.local/src/llm")
  :load-path "~/.local/src/llm"
  :after plz
  )
#+end_src

#+begin_src emacs-lisp :tangle ./emacs/.config/emacs/init.el :mkdirp yes
(use-package ellama
  :if (file-exists-p "~/.local/src/ellama")
  :load-path "~/.local/src/ellama"
  :after llm
  :init
  ;; setup key bindings )
```
This setup was working until today.  Today I pulled the newest commits to all these three git repos.  When I start emacs, I get the following error message with ellama:

**Error (use-package): ellama/:init: Cannot open load file: No such file or directory, plz-event-source**

---

I checked [this issue](https://github.com/s-kostyaev/ellama/issues/123#issue-2341526745),, which looks similar.  The remedy suggested [in there](https://github.com/s-kostyaev/ellama/issues/123#issuecomment-2156382903) is
```
Could you please try to:

    Evaluate https://github.com/ahyatt/llm/blob/main/plz-media-type.el
    Evaluate https://github.com/ahyatt/llm/blob/main/plz-event-source.el
    Try your request again and report back
```
However, the two github links to .el files abovementioned no longer exist.  Looking at llm repo's commit history, I see 2 weeks ago such a commit: https://github.com/ahyatt/llm/commit/c81b44943b2bfeac5114566ab5ad66640bad1e3e -- which might be the reason why the two links no longer correctly resolve.

Are these related to my problem?  How may I solve mine?

**Comment by s-kostyaev** [comment]
You need to install https://elpa.gnu.org/packages/plz-event-source.html. You can install it from gnu elpa or manually, like other packages. But this may lead to problems like this one in the future.
