### ISSUE TITLE
Package not found for fresh installation

### ISSUE THREAD

**Issue by thyeun** [s-kostyaev/ellama#168]
Follow the readme instruction, to install the package, but Melpa cant find it.

![241026_12h16m03s_screenshot](https://github.com/user-attachments/assets/408d1e5b-7f04-4800-abe4-0a4eb929c417)

**Comment by s-kostyaev** [comment]
Package was updated. You need to press `M-x` `package-refresh-contents` `RET` and try again refreshing.
