### ISSUE TITLE
Org-mode support?

### ISSUE THREAD

**Issue by tusharhero** [s-kostyaev/ellama#17]
I wanted to know if we can use Org-mode instead of markdown-mode.

**Comment by s-kostyaev** [comment]
Not sure if models have enough data in org format in training set. I don't think it will works. Maybe we can do it with translation layer inside emacs, but it will make things harder and I can't see what advantages we will get.

Maybe better idea is to support some commands for org mode, but I have no ideas here.

**Comment by s-kostyaev** [comment]
For example if there is code in model response, probably it will be inside markdown code block. Same with lists and tables. What will we see if we try to enable `org-mode` for this type of content? I think something strange.

**Comment by s-kostyaev** [comment]
@tusharhero try new command `ellama-complete` in `org-mode` buffer. Will be soon on `Melpa`.

**Comment by s-kostyaev** [comment]
@tusharhero Implemented. Feedback id welcome.
