### ISSUE TITLE
Problem installing 

### ISSUE THREAD

**Issue by LionyxML** [s-kostyaev/ellama#172]
Hello there!

I did a fresh install today and my Emacs get stuck on the line   `(require 'llm-ollama)` of the example config.

This never happened before and I haven't touched the config since my last re-install some days ago.

I saw something about a new `llm` package version other day, I don't know if anything has to be fixed on the Ellama side, or if this is a 'ME' problem.

**Comment by s-kostyaev** [comment]
Not sure what can go wrong. But looks like problem with your configuration.

**Comment by LionyxML** [comment]
It must have been some instability on melpa/elpa providing packages.

I just uncommented ellama from my config, made a full install and everything works as expected.

Thx!
