### ISSUE TITLE
Wrong diff sent to LLM for commit message for partial commit

### ISSUE THREAD

**Issue by neic** [s-kostyaev/ellama#175]
When using `ellama-generate-commit-message`, I am always getting a generated commit message for the diff for the unstaged changes even though I am committing a partial commit. Since #146 I would expect only the staged changes to be in the diff.

I am not a lips hacker, but I fumbled around a bit with the debugger. It showed that the `(vc-git-diff-switches "--cached")` binding is not picked up by the `vc-git-internal` call:

```
Debugger entered--returning value: ("--histogram")
  #<subr vc-switches>(git diff)
* apply(#<subr vc-switches> (git diff))
* vc-switches(git diff)
  vc-git-diff(nil nil nil #<buffer  *temp*> nil)
  vc-call-backend(Git diff nil nil nil #<buffer  *temp*> nil)
  vc-diff-internal(nil (Git nil) nil nil nil #<buffer  *temp*>)
  ellama--diff-cached()
  ellama-generate-commit-message()
  funcall-interactively(ellama-generate-commit-message)
  command-execute(ellama-generate-commit-message)
```
Found by running `M-x debug-on-entry` `vc-switches` and stepping through with `d`.

I fumbled around a bit more and got it to work by moving the binding around the `with-temp-buffer`:

```elisp
(defun ellama--diff-cached ()
  "Diff staged."
  (let* ((default-directory
	  (if (string= ".git"
		       (car (reverse
			     (cl-remove
			      ""
			      (file-name-split default-directory)
			      :test #'string=))))
	      (file-name-parent-directory default-directory)
	    default-directory))
	 (diff (let ((vc-git-diff-switches "--cached"))
                 (with-temp-buffer
		   (vc-diff-internal
		    nil (vc-deduce-fileset t) nil nil nil (current-buffer))
		   (buffer-substring-no-properties (point-min) (point-max))))))
    (if (string-empty-p diff)
	nil
      diff)))
```

I do not know why the `let` works and the `let*` does not. `(let* ((a 2) (b 3) (c a)) (+ b c))` does eval to `5`.

I can whip up a PR if this solution is the way to fix it.

**Comment by s-kostyaev** [comment]
Hi @neic. Thank you for report and debugging. Please provide a PR. Have you tested your solution?

**Comment by s-kostyaev** [comment]
@neic I can't reproduce your issue. Which emacs version do you have?

**Comment by neic** [comment]
After working on a local updated copy of this repo instead of just fumbling around in the straight repo cache, I cannot reproduce it anymore. It now works as intended!

My best guess is that I somehow had an outdated `ellama.elc` in my straight cache and the code I worked on was not the code that actually ran.

I already wrote up the steps to reproduce it. I'll add it here if this surfaces again.

### Steps to reproduce

- Create a git repo with some example content that is easy to tell apart:
```shell
mkdir ellama-test
cd ellama-test
git init
echo "echo hello world" > test.sh
pwgen 64 1 > password-file
git add .
git commit -m Init
echo "echo hello universe" > test.sh
pwgen 64 1 > password-file
git add test.sh
```
- We now have the `test.sh` change staged, but not the change to `password-file`.

```shell
~/ellama-test% git status
On branch main
Changes to be committed:
  (use "git restore --staged <file>..." to unstage)
	modified:   test.sh

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git restore <file>..." to discard changes in working directory)
	modified:   password-file

~/ellama-test% git diff --cached
diff --git a/test.sh b/test.sh
index 7c0dffd..7b05493 100644
--- a/test.sh
+++ b/test.sh
@@ -1 +1 @@
-echo hello world
+echo hello universe
~/ellama-test% git diff
diff --git a/password-file b/password-file
index 94189cc..3e79944 100644
--- a/password-file
+++ b/password-file
@@ -1 +1 @@
-pae8on4ohzeruehoov0aeD8eiquae5re6uzaekeFahtohVierughie4od8Awaesa
+fohd9tau9biezie3woochegaeTa4ba8Ach7ihiReoPhool8eiThae6see9eiheeg
```

- Open the magit status buffer on the repo and create a commit with `c c`.
- Run  `M-x ellama-generate-commit-message`

The output echoed into the commit message buffer is (in my case):
```
Update password and test script

Updated the password in the password-file and modified the echo message
in the test.sh script.
```
