### ISSUE TITLE
Using Ellama with OpenAI compatible Local API

### ISSUE THREAD

**Issue by neolee** [s-kostyaev/ellama#178]
I know Ellama works great with Ollama, but I'm running my own local server providing OpenAI compatible API (i.e. `http://localhost:1234/` with entry points such as `/v1/models` `/v1/chat/completions` `/v1/completions` `/v1/embeddings`). Any hints on how to configure Ellama to use this kind of setup?

**Comment by s-kostyaev** [comment]
Sure you can do it https://github.com/ahyatt/llm?tab=readme-ov-file#open-ai-compatible

**Comment by neolee** [comment]
Got it, using `llm` is really neat.
