### ISSUE TITLE
Would it be possible to reload or reference a prior session?

### ISSUE THREAD

**Issue by stephenwithav** [s-kostyaev/ellama#18]
I'm a solo developer so I decided to test a daily standup with ellama this morning (ollama backend).  Would it be possible to resume this session tomorrow?

I'm assuming not because Ollama's responses aren't static, but it would be kinda cool.

**Comment by s-kostyaev** [comment]
I will see, how to implement it. Thank you for request.

**Comment by stephenwithav** [comment]
> Could you explain your use case more?

Here's a [gist of this morning's fake standup](https://gist.github.com/stephenwithav/b13383db728533a02459f2ce10fbcb6c).  If promptig in the morning with `ellama-ask` with yesterday's conversation allowed me to resume, it would be helpful.

The context window for llama2 maxes out at 4096, I tthink, so this may be a useless request.

Do you paste the whole log, @tusharhero?  or do you `C-x h M-x ellama-ask-about`?

**Comment by stephenwithav** [comment]
Ollama supports [LoRA](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#adapter)s.  Would it be possible to add to tthe LoRA after each interaction?

**Comment by s-kostyaev** [comment]
> Ollama supports [LoRA](https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#adapter)s. Would it be possible to add to the LoRA after each interaction?

I don't think it will work inside one session without resending previous messages.

**Comment by tusharhero** [comment]
> Do you paste the whole log, @tusharhero? or do you `C-x h M-x ellama-ask-about`?

I just paste the whole thing.

**Comment by s-kostyaev** [comment]
@stephenwithav Feature to manage ellama sessions is planned. I will think more how to implement it. For now you can try to save your standups into file, open it, write new question and use new command `ellama-complete` - it will continue your buffer. Not sure if it will works good, but you can try and return with feedback.

**Comment by stephenwithav** [comment]
Thanks, @s-kostyaev.  I'll test when it's available in MELPA.

**Comment by s-kostyaev** [comment]
> Thanks, @s-kostyaev. I'll test when it's available in MELPA.

It's there. Update ellama and try out.

**Comment by stephenwithav** [comment]
> It's there. Update ellama and try out.

Doom Emacs was the culprit.  I didn't realize `doom sync` required a `-u` flag to update to the newest packages.

My current approach is [here](https://github.com/stephenwithav/Modelfiles/tree/master/fury), so I'll test tomorrow.

Do you still want me to try pasting in the previous days standup each morning?

**Comment by stephenwithav** [comment]
Thanks for the tip, I'll try that.

One thing I find useful is to just `M-:` and use the following expression: `(while t (call-interactively #'ellama-ask))`.  It's as close as I can get to a Bard/ChatGPT-like experience.  Is there a plan to incorporate something like that?

**Comment by s-kostyaev** [comment]
`M-x` `ellama-ask-selection`

**Comment by stephenwithav** [comment]
> `M-x` `ellama-ask-selection`

This just summarized the existing selection.

`ellama-complete` did as well.

**Comment by s-kostyaev** [comment]
Bad. So, you can wait when I will implement proper session saving and loading. It will take some time.

**Comment by stephenwithav** [comment]
The session management definitely has potential.  While I'm unable to resume earlier sessions, it's useful to have a history of earlier chats.

My initial thoughts:

1. Why use `doom-docs-mode` instead of `org-mode`?  The `Suggest edits` and `Help` links don't work.
2. Running concurrent sessions would be useful.
3. Adding the date to the session filename, similar to how `org-journal` works, would be useful.  Each daily standup conversation begins with "Good morning", so `C-c e a i` reloads the earlier session if I accidentally save it.
4. Scratch-buffer style, disposable chats would be useful.
5. `ellama-code-review` buffers aren't interactive.  Should they be?

**Comment by s-kostyaev** [comment]
0. You definitely can resume previous sessions with ellama-load-session.
1. This in your configuration. It's just plain org file.
2. You can have multiple active sessions. You can start new one with C-u ellama-chat
3. I will think about it.
4. I don't understand. Will search it.
5. No. But maybe should be changed.
Thank you for feedback!

**Comment by stephenwithav** [comment]
1. Doom Emacs uses `.org` files in `~/.emacs.d/.local/cache` as Doom Docs.  Changing `ellama-sessions-directory` to `~/.emacs.d/.ellama-sessions` resolved this issue.
2. Doom Emacs uses `SPC u` as an alternative to `C-u`... I didn't realize that.
3. Thanks!
4. The default `*scratch*` buffer is never saved due to changes.  It would be useful, imo, for ellama to have similar buffers that are never saved.  Suppose you can't remember something, like the name of/keybinding from a new-to-you-package, a quick `C-c e i d` for a disposable buffer could be helpful.

Thank you for ellama!
