### ISSUE TITLE
Save and chat in code review session

### ISSUE THREAD

**Issue by aburlot** [s-kostyaev/ellama#181]
I do not know if it is intended, but my code review session are not stored. How could I store it? I also cannot chat in the current session. Is it related?

**Comment by aburlot** [comment]
Hello!
I wanted to ask in the session if an additional improvement would be a good idea. I thought that it could be useful to understand why it chose to change something but not something else. It could allow to start a normal discussion with the model about the review that was provided. The review session could thus be a mix between a discussion and an code improvement task.

**Comment by s-kostyaev** [comment]
Fixed in 0.12.8
