### ISSUE TITLE
error in process sentinel: url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:11434*-340100

### ISSUE THREAD

**Issue by kinredon** [s-kostyaev/ellama#19]
error in process sentinel: url-http-parse-response: Trying to parse HTTP response code in odd buffer:  *http localhost:11434*-340100

**Comment by s-kostyaev** [comment]
Try `M-x` `toggle-debug-on-error` and reproduce an error.

**Comment by kinredon** [comment]
Hi @s-kostyaev, the error information as below:
![image](https://github.com/s-kostyaev/ellama/assets/39270545/6c1c5ae9-1dd2-44a7-9727-6759a6ceaf5d)

**Comment by s-kostyaev** [comment]
@kinredon Looks like you haven't started ollama.

**Comment by s-kostyaev** [comment]
Closind due inactivity. @kinredon feel free to reopen if you still have an issue.
