### ISSUE TITLE
Is this package Emacs 29 required? Got a (void-function pos-eol)

### ISSUE THREAD

**Issue by tepmnthar** [s-kostyaev/ellama#20]
The setopt issue is simple to modify. But what is the pos-eol? I can only find it in emacs 29 changelogs.

**Comment by s-kostyaev** [comment]
Thank you. My linters doesn't catch this.

**Comment by tepmnthar** [comment]
Just replace the (pos-eol) with (line-end-position) in every function and it's ok.

**Comment by s-kostyaev** [comment]
Issue not inside my package, but inside library it uses. See connected issue.
