### ISSUE TITLE
Allow user to scroll (move point) past beginning of currently-being-generated response in *ellama* buffer at their discretion

### ISSUE THREAD

**Issue by suhail-singh** [s-kostyaev/ellama#22]
Currently, when a model is generating a response it doesn't seem possible to scroll past the beginning of the response. Any attempt to do so results in `point` being reverted to the beginning of the response.

## Context and motivation
Some models can generate long responses that extend past the visible area. It is convenient to be able to scroll the output and read the response as it is being generated.

Additionally, some models (e.g. [`starling-lm`](https://huggingface.co/berkeley-nest/Starling-LM-7B-alpha)) can generate runaway responses. In such cases it may be necessary, at times, to be able to review the existing output to determine whether or not the model needs to be forcibly stopped.

**Comment by s-kostyaev** [comment]
Hi @suhail-singh. Thank you for your feedback. I will see how to do it.

**Comment by s-kostyaev** [comment]
@suhail-singh do you need auto scrolling in chat mode only? Or it will be also useful in other cases too?

**Comment by s-kostyaev** [comment]
@suhail-singh Add to your configuration `(setq ellama-auto-scroll t)`. Works for ellama chat buffer only. Disabled by default. Will be soon on package archives.

**Comment by s-kostyaev** [comment]
Second part relates to https://github.com/ahyatt/llm/issues/6

**Comment by s-kostyaev** [comment]
You also can try to create model from existing one in ollama with additional stop parameter like this:
https://github.com/jmorganca/ollama/blob/main/docs/modelfile.md#modelfiles-in-ollamaailibrary

**Comment by s-kostyaev** [comment]
All commands not related to chat in `*ellama*` buffer

**Comment by s-kostyaev** [comment]
User can scroll even without that latest change.

**Comment by s-kostyaev** [comment]
> Sorry, but I don't understand what "not related to chat" specifically means in present context.
> 
> If I understand you correctly, `ellama-ask` would be covered by `ellama-auto-scroll` since it's an alias to `ellama-chat`. Would `ellama-summarize` currently be scrollable as well? If not, yes it would be useful for the output there to be scrollable as well (for the same reasons [as noted above](https://github.com/s-kostyaev/ellama/issues/22#issue-2045688906)).

Summarize not covered by this change.

**Comment by s-kostyaev** [comment]
Now I realized what's the problem. I will fix it.

**Comment by s-kostyaev** [comment]
@suhail-singh check 0.4.3 version - should be fixed.

**Comment by Nebucatnetzer** [comment]
Is there a reason why auto-scroll isn't possible in other buffers as well?
For example I let it generate doc strings and sometimes the generated code scrolls past the visible area which then makes it hard to see when Ellama is finished. This is in a Python buffer.
