### ISSUE TITLE
Completion at point

### ISSUE THREAD

**Issue by carl-reverb** [s-kostyaev/ellama#23]
When coding I often am working in the middle of a file, not at the end. But `ellama-code-complete` and `ellama-code-add` append the buffer. Sometimes I can use `ellama-code-add` and it will replicate everything at the bottom of the buffer, then I can chop the original head of the buffer and use the regenerated code, but it makes me look harder at the git diff to ensure nothing unusual was changed in the regeneration.

Is it possible to `ellama-complete-code-at-point` or `ellama-code-in-selection` or something, which would take the buffer as context but then insert its output inline?

**Comment by carl-reverb** [comment]
I've found sometimes I can use `ellama-change-code` to make an inline change, so maybe that's a sufficient workaround. Thank you for this really excellent package.

**Comment by s-kostyaev** [comment]
Definitely a bug. Thank you for reporting.

**Comment by s-kostyaev** [comment]
@carl-reverb is it works for you now?

**Comment by carl-reverb** [comment]
I think it does, though `zephyr` got carried away and wrote too much!

https://github.com/s-kostyaev/ellama/assets/87382792/ba59ac23-da05-4085-9e7c-a2d69d3e114e
