### ISSUE TITLE
Support Cancellation

### ISSUE THREAD

**Issue by Stebalien** [s-kostyaev/ellama#27]
Once https://github.com/ahyatt/llm/pull/11 is merged and released, it'll be possible to cancel `llm` queries. Ideally:

1. It would be possible to cancel an ongoing query with some interactive function.
2. An ongoing query would automatically be canceled if the buffer from which it was made is closed.

**Comment by tomoya** [comment]
Hi, @Stebalien 

It looks like cancellation is now supported in llm.
https://github.com/ahyatt/llm/commit/f9060bd9d760995c1d47a09a33f91553af1d1b55

P.S.
The ellma is my best elisp in 2023 👍

**Comment by s-kostyaev** [comment]
@tomoya Thank you for the kind words
