### ISSUE TITLE
Should ellama-mode derive from comint-mode

### ISSUE THREAD

**Issue by tvraman** [s-kostyaev/ellama#32]
Would give us prompt navigation etc in a long session for free

**Comment by s-kostyaev** [comment]
I should think about it. Thank you.

**Comment by tvraman** [comment]
markdown does bring its benefits too -- so comint as the major mode might not be such a good idea. Would still be nice to figure out a good way of getting the best of both though

**Comment by mcraveiro** [comment]
Thanks very much for a great mode. One minor quibble, I would love a chat based window which is comint mode derived rather than having to call ```ellama-chat``` for every message - or is there a better way of doing this? Cheers
