### ISSUE TITLE
Consider removing the fill-region call (or limit it to ellama-ask)

### ISSUE THREAD

**Issue by Stebalien** [s-kostyaev/ellama#35]
It tends to mess with code formatting. Personally, I just use `visual-fill-column-mode` but maybe there's a middle ground?

**Comment by s-kostyaev** [comment]
I think we should limit `fill-region` usage to commands without code. I can confirm it leads to problems with code formatting, but I'd like to use it for non-code text.

**Comment by Stebalien** [comment]
Unfortunately, any command can produce code. Although, I guess, markdown will avoid filling code blocks once they have a closing fence.

**Comment by s-kostyaev** [comment]
I think we should for now make new callback like `(formatcb start end)` and set it to `fill-region` for `ellama-chat`

**Comment by s-kostyaev** [comment]
Maybe there is same function, but safe for code. Or we can try to write it ourselfs. Maybe with conditions on major mode or something like that.

**Comment by s-kostyaev** [comment]
We can get some ideas from `auto-fill-mode` - it works fine with both code and text.

**Comment by Stebalien** [comment]
So, there are two separate issues:

1. Joining multiple lines of code together.
2. Wrapping lines of code.

The first case can be solved by preserving all _explicit_ newlines when wrapping. We can do this by:

1. Binding `use-hard-newlines` while reformatting.
2. Setting the `hard` text property to `t` for all newlines explicitly output by the LLM.

I'm not sure how to solve the second case.

**Comment by s-kostyaev** [comment]
> So, there are two separate issues:
> 
> 1. Joining multiple lines of code together.
> 2. Wrapping lines of code.
> 
> The first case can be solved by preserving all _explicit_ newlines when wrapping. We can do this by:
> 
> 1. Binding `use-hard-newlines` while reformatting.
> 2. Setting the `hard` text property to `t` for all newlines explicitly output by the LLM.
> 
> I'm not sure how to solve the second case.

this works:
```emacs-lisp
(add-text-properties start (point) '(hard))
```
But `fill-region` can add newlines inside comments and break the code.

**Comment by s-kostyaev** [comment]
@Stebalien check version 0.4.8

**Comment by s-kostyaev** [comment]
Looks like it doesn't help.

**Comment by s-kostyaev** [comment]
`fill-region` will be called only for non-programming modes. Version 0.4.9

**Comment by s-kostyaev** [comment]
@Stebalien can we close this?

**Comment by Stebalien** [comment]
Yeah, that works reasonably well. It still messes with code blocks in markdown while in-progress, but everything is fine when the command finishes (i.e., once the markdown code block is complete).

Would you mind if I submit a patch to make filling optional (via a customization option)?

**Comment by s-kostyaev** [comment]
> Yeah, that works reasonably well. It still messes with code blocks in markdown while in-progress, but everything is fine when the command finishes (i.e., once the markdown code block is complete).
> 
> Would you mind if I submit a patch to make filling optional (via a customization option)?

Sure. Let it enabled by default.
