### ISSUE TITLE
Emacspeak, ellama-stream and on-done

### ISSUE THREAD

**Issue by tvraman** [s-kostyaev/ellama#36]
If you could make ellama-prompt use ellama-default-on-done  (a variable that is set to #ignore) instead of using #'ignore directly, I could then set that var to an emacspeak-specific function that plays a sound

**Comment by s-kostyaev** [comment]
Should it be called with all commands or with specific one only (ellama-chat, probably)?

**Comment by tvraman** [comment]
Sergey Kostyaev ***@***.***> writes:

I think it would be best to have  a named function as  the callback for
each of the ellama commands -- rather than an anonymous lambda as at
present. Then Emacspeak could define appropriate advice on each of them,
rather than having a one-size fits all behavior on the speech-side; as
an example, one might want it to automaticaly speak the response from
the LLM for some commands and not others.

> Should it be called with all commands or with specific one only
> (ellama-chat, probably)?
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you authored the thread.
>

--

**Comment by s-kostyaev** [comment]
Makes sense. Thank you.

**Comment by tvraman** [comment]
See PR 43
