### ISSUE TITLE
Configurable default prompts ?

### ISSUE THREAD

**Issue by beniz** [s-kostyaev/ellama#37]
Hello, great work, very useful !
I was wondering whether there's a way (or should one be added) to configure the default prompts such as 
https://github.com/s-kostyaev/ellama/blob/cb0fbac035ce76985e85d071e960901b39269112/ellama.el#L315 ?

Reason is that when dealing with some other language than English, the English prompt appears to `"lock"` the model into English despite the selection being in another language.

**Comment by s-kostyaev** [comment]
Hi, @beniz. That makes sense. I will think how to do it.

**Comment by beniz** [comment]
Thanks @s-kostyaev

**Comment by oatmealm** [comment]
I was looking to see if it's possible to select prompt directives like it's done in gptel... if I understand correctly, inf ellama they're predefined and will be sent for me with the query, depending on the type of query? Is it possible to interactively select a prompt directive while I'm already in a chat session to change the context or something similar?

**Comment by s-kostyaev** [comment]
@oatmealm for now if you want to change query you may use something like ellama-chat or ellama-ask-about. It is not possible to change predefined prompts interactively. Could you provide use case for that?

**Comment by oatmealm** [comment]
> @oatmealm for now if you want to change query you may use something like ellama-chat or ellama-ask-about. It is not possible to change predefined prompts interactively. Could you provide use case for that?

It's still rather new to me and I'm assuming it's a useful feature. 

From my experience with some apps, especially Amollo and Enchant for iOS, I can create sessions with a local (?) prompt which sets a premise, for example:  

you're an expert on topic x, your replies are concise and you always cite your sources. 

I can switch between various such sessions, where context and expectations are established, and then continue and ask more questions. 

From what I've seen in gptel there's only one chat sessions (also ellama ?) but one can keep a set of pre-defined directives to choose from, and essentially change the expertise of the model (or its focus) on demand in the active session. 

So both approaches are useful imho and this directives really help in producing better results from the model.

**Comment by s-kostyaev** [comment]
> From what I've seen in gptel there's only one chat sessions (also ellama ?) 

Temporary. I working on session management for ellama

**Comment by s-kostyaev** [comment]
> you're an expert on topic x, your replies are concise and you always cite your sources.

This need more work to be useful. Like in OpenAI's GPTs we should can use tools and data sources. Without it this feature looks useless. But I can be wrong. If I see how to improve user experience I will do it.

**Comment by s-kostyaev** [comment]
@beniz I added translation pipeline for chat. Maybe useful if there is powerful model (mixtral, for example) that better understands english. You may use it as `ellama-provider` and other model, that better understand your language (openchat in my case) as translator between you and that powerful model.
