### ISSUE TITLE
ellama-ask-line

### ISSUE THREAD

**Issue by tvraman** [s-kostyaev/ellama#46]
any reason this is a defalias  of an anonymous lambda rather than a plain defun?

**Comment by s-kostyaev** [comment]
What do you mean? I don't understand.

**Comment by s-kostyaev** [comment]
In latest main there are no calls to defalias.

**Comment by tvraman** [comment]
Apologies -- I was likely looking at something old or stale in my
snapshot in git. Thanks for removing all the defalias calls.
--
