### ISSUE TITLE
Failing to get results

### ISSUE THREAD

**Issue by acastanedam** [s-kostyaev/ellama#50]
Hi, I do not know if it is my misusage or misconfiguration of ellama, but every time I try a call I get the error:
`error in process filter: llm-request-callback-in-buffer: Wrong number of arguments: (2 . 2), 1`
and although the buffer is opened no answer is printed.
The ollama server is properly setup and the CLI is working, do I need to start it from emacs?
Thanks in advance for your help

**Comment by s-kostyaev** [comment]
Hi @acastanedam 

Try to `M-x` `toggle-debug-on-error` and reproduce issue and paste debug trace here.

**Comment by acastanedam** [comment]
Hi @s-kostyaev, I apologize. The provider in `(setopt ellama-provider ())` was pointing to a tag not present in the system. Thanks for your help and this tool. 
Best
