### ISSUE TITLE
Typos in prompts

### ISSUE THREAD

**Issue by gvalson** [s-kostyaev/ellama#51]
Hi, thanks for this excellent package.

I was looking through the source code and found that there are typos in the hardcoded prompts. For example:

> "Regarding the following code, %s, only **ouput** the result code in format \```language\n...\n```:\n```\n%s\n```"

This typo appears in:

- `ellama-change-code`
- `ellama-enhance-code`
- `ellama-add-code`

**Comment by s-kostyaev** [comment]
Hi @gvalson
Thank you for report. Will fix soon.
