### ISSUE TITLE
Default session names with / try to create directories.

### ISSUE THREAD

**Issue by stephenwithav** [s-kostyaev/ellama#55]
`<s>[INST] Explain emacs. [/INST]` attempts to create a directory in `ellama-sessions` because of the`/` in `[/INST]`.

Replacing `/` with underscores in `ellama-session-file` will prevent that.

Should I submit a PR with that slight `ellama-generate-name` refactor?

**Comment by s-kostyaev** [comment]
Sure. Have you signed FSF papers?

**Comment by s-kostyaev** [comment]
Why you send template into ollama? It should be filled on ollama side. Or you use another llm provider?

**Comment by stephenwithav** [comment]
I use Ollama.  I watched [this video](https://www.youtube.com/watch?v=f32dc5M2Mn0) on [Prompt-Engineering for Open-Source LLMs](https://www.youtube.com/watch?v=f32dc5M2Mn0) and it mentioned using that structure, which worked well with llama2-based models.

I haven't checked the `llm` package to learn if it wraps inputs with any tags or not.

**Comment by stephenwithav** [comment]
For more clarification, I like to test new prompts interactively.  Using the `<s>[INST][/INST]` format appears to provide more consistent responses.  After reading an article yesterday, I used the following prompt:

`<s>[INST] I will ask you a biochemistry question.  You will provide a thorough, step-by-step answer to me as if I were a high-school freshmen currently enrolled in biology. [/INST] </s> Alabama wants to execute a man using nitrogen gas.  How would that kill a man?  Provide a step-by-step explanation.`

That provided a more concise answer than without the tags.

**Comment by s-kostyaev** [comment]
You can create new ollama model with this prompt template and use it with ellama. See modelfile documentation of ollama.

**Comment by stephenwithav** [comment]
Yes, I'm familiar with that.  My thought is this change will make it easier to iterate on prompts when designing new ones.

**Comment by s-kostyaev** [comment]
Sure, we need this change. Case just looks strange to me

**Comment by stephenwithav** [comment]
Thanks.  This will also prevent errors in filenames like either/or, true/false, yes/no, etc.
