### ISSUE TITLE
Provide "mode selection" option

### ISSUE THREAD

**Issue by Stebalien** [s-kostyaev/ellama#57]
Right now, one needs to change 3 different settings to switch from markdown to org-mode and it feels really hacky. Instead, I'd:

1. Have a simple `ellama-major-mode` customization option where the user can select between a set of pre-defined modes.
2. based on the mode, define the extension, nick prefix, formatting logic, etc.

**Comment by Stebalien** [comment]
(this is purely a suggestion, not a bug report)

**Comment by s-kostyaev** [comment]
It will work for closed set of modes. Like org and markdown only. But maybe useful. I will think about it, thank you.

**Comment by Stebalien** [comment]
Another way to do this is with "classes". I.e.:

1. Define a class with a set of methods for initializing the buffer, adding a header, etc.
2. Implement the class for a few modes.
3. Let users define custom ones.

**Comment by s-kostyaev** [comment]
Sounds interesting, but [help wanted] 🙂

**Comment by stephenwithav** [comment]
@Stebalien Can you give an example/walkthrough of what you'd like?

**Comment by Stebalien** [comment]
From a user perspective, a setting like `ollama-chat-mode` (or something like that) that I can set to `org`, `markdown`, or `text`. That setting should ensure that:

1. Session files get the correct extensions.
2. The correct mode is set for chat buffers.
3. Text is filtered/translated from markdown to the appropriate format.

From an implementation perspective, there are a bunch of ways of doing this (classes, generics, specially named groups of functions, alists of functions, etc.).

**Comment by stephenwithav** [comment]
Thanks.  Step 3 will likely be the most difficult.  I will start work on this as soon as I finish testing having two ellama sessions chat with each other tonight.

**Comment by s-kostyaev** [comment]
Step 3 already implemented 🙂

**Comment by s-kostyaev** [comment]
Also, @stephenwithav have you signed FSF papers?

**Comment by stephenwithav** [comment]
I have, @s-kostyaev, I think.  No harm signing again, though.  Where's the link?

**Comment by s-kostyaev** [comment]
If you already have, no need to sign second time.

**Comment by Stebalien** [comment]
> Where's the link?

You have to print a document, sign it, scan it, then email it back. If you don't remember doing that, you probably didn't sign the papers (https://www.fsf.org/licensing/contributor-faq).

**Comment by stephenwithav** [comment]
Everything's signed now.  I'll tackle this issue this weekend.
