### ISSUE TITLE
Provide a way to specify a mode for "non-instant" questions.

### ISSUE THREAD

**Issue by Stebalien** [s-kostyaev/ellama#58]
Unfortunately, while the old mode option worked everywhere, `ellama-instant-mode` only applies to "instant" questions. `ellama-chat` relies entirely on the extension.

Alternatively, maybe consider providing a hook? Basically, I'd _like_ to use `markdown-view-mode` instead of `markdown-mode`, but there's no longer a way to do that.

**Comment by s-kostyaev** [comment]
Fixed in 0.7.3

**Comment by Stebalien** [comment]
Thank you!
