### ISSUE TITLE
Update selected region is not working.

### ISSUE THREAD

**Issue by hwiorn** [s-kostyaev/ellama#6]
Ellama's update often causes issues when using the "selected-region" feature as it may remove the selected region and insert new content at the end of a line, leading to unexpected results.

## Reproduce
1. Make a new buffer
2. `M-x markdown-mode`
3. Paste text: "Ellama lets you access LLMs locally using ollama's API from Emacs. It offers a set of commands that allow you to inquire, define words, translate text and more through the Emacs interface. Ellama natively supports streaming output, making it effortless to use with your preferred text editor."
3. Select region: "**[Ellama lets you access LLMs locally using ollama's API from Emacs.]** It offers a set of commands that allow you to inquire, define words, translate text and more through the Emacs interface. Ellama natively supports streaming output, making it effortless to use with your preferred text editor."
4. Do `M-x ellama-enhance-wording`
" It offers a set of commands that allow you to inquire, define words, translate text and more through the Emacs interface. Ellama natively supports streaming output, making it effortless to use with your preferred text editor. **Ellama enables you to connect with local LLMs through its API, making use of Ollama within Emacs for seamless integration.**"

**Comment by s-kostyaev** [comment]
Thank you for reporting this @hwiorn
