### ISSUE TITLE
Avoid advising global functions

### ISSUE THREAD

**Issue by Stebalien** [s-kostyaev/ellama#60]
Please try to avoid advising global functions for mode-local functionality. Advice is a last-ditch "there's no other way" method.

- Instead of advising keyboard-quit, create a `ellama-session-mode` and bind `[remap keyboard-quit]` in its keymap.
- Instead of advising `kill-buffer`, add a buffer-local hook to `kill-buffer-hook`.
- Instead of advising `save-buffer`, add a buffer-local function to `write-file-functions` and return non-nil.

**Comment by s-kostyaev** [comment]
Today I learn. Thank you. I will fix it.

**Comment by Stebalien** [comment]
Ah, sorry, I was already working on a fix. See #62.

**Comment by s-kostyaev** [comment]
@Stebalien Merged. But after merge I realized that it breaks request cancel functionality for non-chat and non-instant buffers. Like `ellama-add-code`, `ellama-complete` or `ellama-make-concise`.

**Comment by s-kostyaev** [comment]
@Stebalien Thank you!

**Comment by Stebalien** [comment]
> I will fix it now by enable ellama-instant-mode in this buffers.

In that case, I'd consider renaming it to something like `ellama-request-mode` and only turning it on while the request is ongoing (maybe even in `ellama-session-mode` buffers?).

**Comment by s-kostyaev** [comment]
Since its changes buffer-local I don't think we should turn it off. But move it into `ellama-stream` looks promising... Maybe it's good idea

**Comment by Stebalien** [comment]
Yeah, I guess there's little harm in leaving it on. I was just thinking users might want to bind keys that are only active when actively querying ellama.

**Comment by s-kostyaev** [comment]
@Stebalien see #67
