### ISSUE TITLE
Prefer `read` over `eval` for storing sessions

### ISSUE THREAD

**Issue by Stebalien** [s-kostyaev/ellama#63]
I see you're saving a file with `(setq ellama--current-session ...`. A slightly safer way to do this is to store _just_ the data and use `read` to load it. Unlike `eval`, that won't execute any code (so it's safer to, e.g., share session files with others).

**Comment by s-kostyaev** [comment]
I have tried it already, but without success. I agree that this is safer.

**Comment by Stebalien** [comment]
Hm. I did a basic test and it looked like it had no issues reading hash tables. Do you happen to remember the error?

The following _should_ work:

```elisp
(with-temp-buffer
  (insert-file-contents ".session.el")
  (goto-char (point-min))
  (read (current-buffer)))
```

**Comment by s-kostyaev** [comment]
Probably I have used it wrong. It works. I will fix it.
