### ISSUE TITLE
Uses keybindings reserved for end user customisation

### ISSUE THREAD

**Issue by purcell** [s-kostyaev/ellama#72]
Hi! I noticed that this package binds `C-c e`: that's among the keys you should never bind from a package, see the [corresponding Emacs doc](https://www.gnu.org/software/emacs/manual/html_node/elisp/Key-Binding-Conventions.html).

What I'd recommend would be _either_ picking a different prefix like `C-c C-e`, or - better IMO - doing something [like this](https://github.com/purcell/envrc/blob/master/envrc.el#L118-L122).

I'm going to test-drive this package, which is how I noticed this.

All the best!

**Comment by s-kostyaev** [comment]
Hi @purcell!
Thank you for report, I will fix it. And thank you for link to example how to fix it.

**Comment by s-kostyaev** [comment]
@purcell fixed in 0.8.4

**Comment by purcell** [comment]
Nice! 🙌
